'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.ComponentModel.DataAnnotations

Public Enum OrderType As Integer
    <Display(Name:="普通")>
    Normal = 0
    <Display(Name:="拼单")>
    Merge = 1
End Enum
