'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Public Enum OrderStatus As Integer
    Unconfirm = 0
    Confirm = 1
    Booked = 2
    Recieved = 3
    Complete = 4
End Enum
