'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.ComponentModel.DataAnnotations

Public Enum OrderStatus As Integer
    <Display(Name:="未确定")>
    Unconfirm = 0
    <Display(Name:="确定")>
    Confirm = 1
    <Display(Name:="已下单")>
    Booked = 2
    <Display(Name:="已收货")>
    Recieved = 3
    <Display(Name:="已完成")>
    Complete = 4
End Enum
