'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Post
    Public Property Id As Integer
    Public Property Title As String
    Public Property ShortDescription As String
    Public Property Description As String
    Public Property Meta As String
    Public Property UrlSlug As String
    Public Property Published As Nullable(Of Boolean)
    Public Property PostedOn As Nullable(Of Date)
    Public Property Modified As Nullable(Of Date)
    Public Property CategoryId As Integer
    Public Property Author As String

    Public Overridable Property Category As Category
    Public Overridable Property Tags As ICollection(Of Tag) = New HashSet(Of Tag)

End Class
