'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tag
    Public Property Id As Integer
    Public Property Name As String
    Public Property UrlSlug As String
    Public Property Description As String

    Public Overridable Property Posts As ICollection(Of Post) = New HashSet(Of Post)

End Class
