'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WcfService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OrderDto", [Namespace]:="http://schemas.datacontract.org/2004/07/OrderManagement.WcfService.Dto"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OrderDto
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerDtoField As WcfService.CustomerDto
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FreightField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InvoiceNoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderDateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderDetailDtoesField() As WcfService.OrderDetailDto
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderTypeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ShipDateField As System.Nullable(Of Date)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomerDto() As WcfService.CustomerDto
            Get
                Return Me.CustomerDtoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomerDtoField, value) <> true) Then
                    Me.CustomerDtoField = value
                    Me.RaisePropertyChanged("CustomerDto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomerId() As Integer
            Get
                Return Me.CustomerIdField
            End Get
            Set
                If (Me.CustomerIdField.Equals(value) <> true) Then
                    Me.CustomerIdField = value
                    Me.RaisePropertyChanged("CustomerId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Freight() As System.Nullable(Of Decimal)
            Get
                Return Me.FreightField
            End Get
            Set
                If (Me.FreightField.Equals(value) <> true) Then
                    Me.FreightField = value
                    Me.RaisePropertyChanged("Freight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InvoiceNo() As String
            Get
                Return Me.InvoiceNoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InvoiceNoField, value) <> true) Then
                    Me.InvoiceNoField = value
                    Me.RaisePropertyChanged("InvoiceNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderDate() As System.Nullable(Of Date)
            Get
                Return Me.OrderDateField
            End Get
            Set
                If (Me.OrderDateField.Equals(value) <> true) Then
                    Me.OrderDateField = value
                    Me.RaisePropertyChanged("OrderDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderDetailDtoes() As WcfService.OrderDetailDto()
            Get
                Return Me.OrderDetailDtoesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrderDetailDtoesField, value) <> true) Then
                    Me.OrderDetailDtoesField = value
                    Me.RaisePropertyChanged("OrderDetailDtoes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderId() As Integer
            Get
                Return Me.OrderIdField
            End Get
            Set
                If (Me.OrderIdField.Equals(value) <> true) Then
                    Me.OrderIdField = value
                    Me.RaisePropertyChanged("OrderId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderType() As Integer
            Get
                Return Me.OrderTypeField
            End Get
            Set
                If (Me.OrderTypeField.Equals(value) <> true) Then
                    Me.OrderTypeField = value
                    Me.RaisePropertyChanged("OrderType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ShipDate() As System.Nullable(Of Date)
            Get
                Return Me.ShipDateField
            End Get
            Set
                If (Me.ShipDateField.Equals(value) <> true) Then
                    Me.ShipDateField = value
                    Me.RaisePropertyChanged("ShipDate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CustomerDto", [Namespace]:="http://schemas.datacontract.org/2004/07/OrderManagement.WcfService.Dto"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CustomerDto
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PhoneField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PostCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TaobaoNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WechatNameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address() As String
            Get
                Return Me.AddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddressField, value) <> true) Then
                    Me.AddressField = value
                    Me.RaisePropertyChanged("Address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomerId() As Integer
            Get
                Return Me.CustomerIdField
            End Get
            Set
                If (Me.CustomerIdField.Equals(value) <> true) Then
                    Me.CustomerIdField = value
                    Me.RaisePropertyChanged("CustomerId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Phone() As String
            Get
                Return Me.PhoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PhoneField, value) <> true) Then
                    Me.PhoneField = value
                    Me.RaisePropertyChanged("Phone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PostCode() As String
            Get
                Return Me.PostCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PostCodeField, value) <> true) Then
                    Me.PostCodeField = value
                    Me.RaisePropertyChanged("PostCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TaobaoName() As String
            Get
                Return Me.TaobaoNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TaobaoNameField, value) <> true) Then
                    Me.TaobaoNameField = value
                    Me.RaisePropertyChanged("TaobaoName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property WechatName() As String
            Get
                Return Me.WechatNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WechatNameField, value) <> true) Then
                    Me.WechatNameField = value
                    Me.RaisePropertyChanged("WechatName")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OrderDetailDto", [Namespace]:="http://schemas.datacontract.org/2004/07/OrderManagement.WcfService.Dto"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OrderDetailDto
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LinkField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderDetailIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductDtoField As WcfService.ProductDto
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PurchasePriceField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QuantityField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SoldPriceField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Link() As String
            Get
                Return Me.LinkField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LinkField, value) <> true) Then
                    Me.LinkField = value
                    Me.RaisePropertyChanged("Link")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderDetailId() As Integer
            Get
                Return Me.OrderDetailIdField
            End Get
            Set
                If (Me.OrderDetailIdField.Equals(value) <> true) Then
                    Me.OrderDetailIdField = value
                    Me.RaisePropertyChanged("OrderDetailId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderId() As Integer
            Get
                Return Me.OrderIdField
            End Get
            Set
                If (Me.OrderIdField.Equals(value) <> true) Then
                    Me.OrderIdField = value
                    Me.RaisePropertyChanged("OrderId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProductDto() As WcfService.ProductDto
            Get
                Return Me.ProductDtoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductDtoField, value) <> true) Then
                    Me.ProductDtoField = value
                    Me.RaisePropertyChanged("ProductDto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProductId() As Integer
            Get
                Return Me.ProductIdField
            End Get
            Set
                If (Me.ProductIdField.Equals(value) <> true) Then
                    Me.ProductIdField = value
                    Me.RaisePropertyChanged("ProductId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PurchasePrice() As System.Nullable(Of Decimal)
            Get
                Return Me.PurchasePriceField
            End Get
            Set
                If (Me.PurchasePriceField.Equals(value) <> true) Then
                    Me.PurchasePriceField = value
                    Me.RaisePropertyChanged("PurchasePrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Quantity() As System.Nullable(Of Integer)
            Get
                Return Me.QuantityField
            End Get
            Set
                If (Me.QuantityField.Equals(value) <> true) Then
                    Me.QuantityField = value
                    Me.RaisePropertyChanged("Quantity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SoldPrice() As System.Nullable(Of Decimal)
            Get
                Return Me.SoldPriceField
            End Get
            Set
                If (Me.SoldPriceField.Equals(value) <> true) Then
                    Me.SoldPriceField = value
                    Me.RaisePropertyChanged("SoldPrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As Integer
            Get
                Return Me.StatusField
            End Get
            Set
                If (Me.StatusField.Equals(value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ProductDto", [Namespace]:="http://schemas.datacontract.org/2004/07/OrderManagement.WcfService.Dto"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ProductDto
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BrandIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductNameJpField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SpeciesIdField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BrandId() As Integer
            Get
                Return Me.BrandIdField
            End Get
            Set
                If (Me.BrandIdField.Equals(value) <> true) Then
                    Me.BrandIdField = value
                    Me.RaisePropertyChanged("BrandId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProductId() As Integer
            Get
                Return Me.ProductIdField
            End Get
            Set
                If (Me.ProductIdField.Equals(value) <> true) Then
                    Me.ProductIdField = value
                    Me.RaisePropertyChanged("ProductId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProductName() As String
            Get
                Return Me.ProductNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductNameField, value) <> true) Then
                    Me.ProductNameField = value
                    Me.RaisePropertyChanged("ProductName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProductNameJp() As String
            Get
                Return Me.ProductNameJpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductNameJpField, value) <> true) Then
                    Me.ProductNameJpField = value
                    Me.RaisePropertyChanged("ProductNameJp")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SpeciesId() As Integer
            Get
                Return Me.SpeciesIdField
            End Get
            Set
                If (Me.SpeciesIdField.Equals(value) <> true) Then
                    Me.SpeciesIdField = value
                    Me.RaisePropertyChanged("SpeciesId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OrderSearchConditionsDto", [Namespace]:="http://schemas.datacontract.org/2004/07/OrderManagement.WcfService.Dto"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OrderSearchConditionsDto
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderDateFromField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderDateToField As System.Nullable(Of Date)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomerId() As Integer
            Get
                Return Me.CustomerIdField
            End Get
            Set
                If (Me.CustomerIdField.Equals(value) <> true) Then
                    Me.CustomerIdField = value
                    Me.RaisePropertyChanged("CustomerId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderDateFrom() As System.Nullable(Of Date)
            Get
                Return Me.OrderDateFromField
            End Get
            Set
                If (Me.OrderDateFromField.Equals(value) <> true) Then
                    Me.OrderDateFromField = value
                    Me.RaisePropertyChanged("OrderDateFrom")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderDateTo() As System.Nullable(Of Date)
            Get
                Return Me.OrderDateToField
            End Get
            Set
                If (Me.OrderDateToField.Equals(value) <> true) Then
                    Me.OrderDateToField = value
                    Me.RaisePropertyChanged("OrderDateTo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DbProcessResult", [Namespace]:="http://schemas.datacontract.org/2004/07/OrderManagement.WcfService.Results"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DbProcessResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorMessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsSuccessField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.ErrorMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorMessageField, value) <> true) Then
                    Me.ErrorMessageField = value
                    Me.RaisePropertyChanged("ErrorMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsSuccess() As Boolean
            Get
                Return Me.IsSuccessField
            End Get
            Set
                If (Me.IsSuccessField.Equals(value) <> true) Then
                    Me.IsSuccessField = value
                    Me.RaisePropertyChanged("IsSuccess")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WcfService.IOrderManagementService")>  _
    Public Interface IOrderManagementService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/GetOrderDto", ReplyAction:="http://tempuri.org/IOrderManagementService/GetOrderDtoResponse")>  _
        Function GetOrderDto(ByVal orderId As Integer) As WcfService.OrderDto
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/GetOrderDto", ReplyAction:="http://tempuri.org/IOrderManagementService/GetOrderDtoResponse")>  _
        Function GetOrderDtoAsync(ByVal orderId As Integer) As System.Threading.Tasks.Task(Of WcfService.OrderDto)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/GetOrderDtoes", ReplyAction:="http://tempuri.org/IOrderManagementService/GetOrderDtoesResponse")>  _
        Function GetOrderDtoes() As WcfService.OrderDto()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/GetOrderDtoes", ReplyAction:="http://tempuri.org/IOrderManagementService/GetOrderDtoesResponse")>  _
        Function GetOrderDtoesAsync() As System.Threading.Tasks.Task(Of WcfService.OrderDto())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/GetOrderDtoesByConditions", ReplyAction:="http://tempuri.org/IOrderManagementService/GetOrderDtoesByConditionsResponse")>  _
        Function GetOrderDtoesByConditions(ByVal conditions As WcfService.OrderSearchConditionsDto) As WcfService.OrderDto()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/GetOrderDtoesByConditions", ReplyAction:="http://tempuri.org/IOrderManagementService/GetOrderDtoesByConditionsResponse")>  _
        Function GetOrderDtoesByConditionsAsync(ByVal conditions As WcfService.OrderSearchConditionsDto) As System.Threading.Tasks.Task(Of WcfService.OrderDto())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/GetCustomerDtoes", ReplyAction:="http://tempuri.org/IOrderManagementService/GetCustomerDtoesResponse")>  _
        Function GetCustomerDtoes() As WcfService.CustomerDto()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/GetCustomerDtoes", ReplyAction:="http://tempuri.org/IOrderManagementService/GetCustomerDtoesResponse")>  _
        Function GetCustomerDtoesAsync() As System.Threading.Tasks.Task(Of WcfService.CustomerDto())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/GetCustomerDto", ReplyAction:="http://tempuri.org/IOrderManagementService/GetCustomerDtoResponse")>  _
        Function GetCustomerDto(ByVal customerId As String) As WcfService.CustomerDto
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/GetCustomerDto", ReplyAction:="http://tempuri.org/IOrderManagementService/GetCustomerDtoResponse")>  _
        Function GetCustomerDtoAsync(ByVal customerId As String) As System.Threading.Tasks.Task(Of WcfService.CustomerDto)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/GetCustomerDtoByCondition", ReplyAction:="http://tempuri.org/IOrderManagementService/GetCustomerDtoByConditionResponse")>  _
        Function GetCustomerDtoByCondition(ByVal condition As WcfService.CustomerDto) As WcfService.CustomerDto()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/GetCustomerDtoByCondition", ReplyAction:="http://tempuri.org/IOrderManagementService/GetCustomerDtoByConditionResponse")>  _
        Function GetCustomerDtoByConditionAsync(ByVal condition As WcfService.CustomerDto) As System.Threading.Tasks.Task(Of WcfService.CustomerDto())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/AddCustomerDto", ReplyAction:="http://tempuri.org/IOrderManagementService/AddCustomerDtoResponse")>  _
        Function AddCustomerDto(ByVal leadTimeDto As WcfService.CustomerDto) As WcfService.DbProcessResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/AddCustomerDto", ReplyAction:="http://tempuri.org/IOrderManagementService/AddCustomerDtoResponse")>  _
        Function AddCustomerDtoAsync(ByVal leadTimeDto As WcfService.CustomerDto) As System.Threading.Tasks.Task(Of WcfService.DbProcessResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/UpdateCustomerDto", ReplyAction:="http://tempuri.org/IOrderManagementService/UpdateCustomerDtoResponse")>  _
        Function UpdateCustomerDto(ByVal leadTimeDto As WcfService.CustomerDto) As WcfService.DbProcessResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/UpdateCustomerDto", ReplyAction:="http://tempuri.org/IOrderManagementService/UpdateCustomerDtoResponse")>  _
        Function UpdateCustomerDtoAsync(ByVal leadTimeDto As WcfService.CustomerDto) As System.Threading.Tasks.Task(Of WcfService.DbProcessResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/DeleteCustomerDto", ReplyAction:="http://tempuri.org/IOrderManagementService/DeleteCustomerDtoResponse")>  _
        Function DeleteCustomerDto(ByVal customerId As String) As WcfService.DbProcessResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/DeleteCustomerDto", ReplyAction:="http://tempuri.org/IOrderManagementService/DeleteCustomerDtoResponse")>  _
        Function DeleteCustomerDtoAsync(ByVal customerId As String) As System.Threading.Tasks.Task(Of WcfService.DbProcessResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/CustomerDtoExists", ReplyAction:="http://tempuri.org/IOrderManagementService/CustomerDtoExistsResponse")>  _
        Function CustomerDtoExists(ByVal customerId As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/CustomerDtoExists", ReplyAction:="http://tempuri.org/IOrderManagementService/CustomerDtoExistsResponse")>  _
        Function CustomerDtoExistsAsync(ByVal customerId As String) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IOrderManagementServiceChannel
        Inherits WcfService.IOrderManagementService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class OrderManagementServiceClient
        Inherits System.ServiceModel.ClientBase(Of WcfService.IOrderManagementService)
        Implements WcfService.IOrderManagementService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetOrderDto(ByVal orderId As Integer) As WcfService.OrderDto Implements WcfService.IOrderManagementService.GetOrderDto
            Return MyBase.Channel.GetOrderDto(orderId)
        End Function
        
        Public Function GetOrderDtoAsync(ByVal orderId As Integer) As System.Threading.Tasks.Task(Of WcfService.OrderDto) Implements WcfService.IOrderManagementService.GetOrderDtoAsync
            Return MyBase.Channel.GetOrderDtoAsync(orderId)
        End Function
        
        Public Function GetOrderDtoes() As WcfService.OrderDto() Implements WcfService.IOrderManagementService.GetOrderDtoes
            Return MyBase.Channel.GetOrderDtoes
        End Function
        
        Public Function GetOrderDtoesAsync() As System.Threading.Tasks.Task(Of WcfService.OrderDto()) Implements WcfService.IOrderManagementService.GetOrderDtoesAsync
            Return MyBase.Channel.GetOrderDtoesAsync
        End Function
        
        Public Function GetOrderDtoesByConditions(ByVal conditions As WcfService.OrderSearchConditionsDto) As WcfService.OrderDto() Implements WcfService.IOrderManagementService.GetOrderDtoesByConditions
            Return MyBase.Channel.GetOrderDtoesByConditions(conditions)
        End Function
        
        Public Function GetOrderDtoesByConditionsAsync(ByVal conditions As WcfService.OrderSearchConditionsDto) As System.Threading.Tasks.Task(Of WcfService.OrderDto()) Implements WcfService.IOrderManagementService.GetOrderDtoesByConditionsAsync
            Return MyBase.Channel.GetOrderDtoesByConditionsAsync(conditions)
        End Function
        
        Public Function GetCustomerDtoes() As WcfService.CustomerDto() Implements WcfService.IOrderManagementService.GetCustomerDtoes
            Return MyBase.Channel.GetCustomerDtoes
        End Function
        
        Public Function GetCustomerDtoesAsync() As System.Threading.Tasks.Task(Of WcfService.CustomerDto()) Implements WcfService.IOrderManagementService.GetCustomerDtoesAsync
            Return MyBase.Channel.GetCustomerDtoesAsync
        End Function
        
        Public Function GetCustomerDto(ByVal customerId As String) As WcfService.CustomerDto Implements WcfService.IOrderManagementService.GetCustomerDto
            Return MyBase.Channel.GetCustomerDto(customerId)
        End Function
        
        Public Function GetCustomerDtoAsync(ByVal customerId As String) As System.Threading.Tasks.Task(Of WcfService.CustomerDto) Implements WcfService.IOrderManagementService.GetCustomerDtoAsync
            Return MyBase.Channel.GetCustomerDtoAsync(customerId)
        End Function
        
        Public Function GetCustomerDtoByCondition(ByVal condition As WcfService.CustomerDto) As WcfService.CustomerDto() Implements WcfService.IOrderManagementService.GetCustomerDtoByCondition
            Return MyBase.Channel.GetCustomerDtoByCondition(condition)
        End Function
        
        Public Function GetCustomerDtoByConditionAsync(ByVal condition As WcfService.CustomerDto) As System.Threading.Tasks.Task(Of WcfService.CustomerDto()) Implements WcfService.IOrderManagementService.GetCustomerDtoByConditionAsync
            Return MyBase.Channel.GetCustomerDtoByConditionAsync(condition)
        End Function
        
        Public Function AddCustomerDto(ByVal leadTimeDto As WcfService.CustomerDto) As WcfService.DbProcessResult Implements WcfService.IOrderManagementService.AddCustomerDto
            Return MyBase.Channel.AddCustomerDto(leadTimeDto)
        End Function
        
        Public Function AddCustomerDtoAsync(ByVal leadTimeDto As WcfService.CustomerDto) As System.Threading.Tasks.Task(Of WcfService.DbProcessResult) Implements WcfService.IOrderManagementService.AddCustomerDtoAsync
            Return MyBase.Channel.AddCustomerDtoAsync(leadTimeDto)
        End Function
        
        Public Function UpdateCustomerDto(ByVal leadTimeDto As WcfService.CustomerDto) As WcfService.DbProcessResult Implements WcfService.IOrderManagementService.UpdateCustomerDto
            Return MyBase.Channel.UpdateCustomerDto(leadTimeDto)
        End Function
        
        Public Function UpdateCustomerDtoAsync(ByVal leadTimeDto As WcfService.CustomerDto) As System.Threading.Tasks.Task(Of WcfService.DbProcessResult) Implements WcfService.IOrderManagementService.UpdateCustomerDtoAsync
            Return MyBase.Channel.UpdateCustomerDtoAsync(leadTimeDto)
        End Function
        
        Public Function DeleteCustomerDto(ByVal customerId As String) As WcfService.DbProcessResult Implements WcfService.IOrderManagementService.DeleteCustomerDto
            Return MyBase.Channel.DeleteCustomerDto(customerId)
        End Function
        
        Public Function DeleteCustomerDtoAsync(ByVal customerId As String) As System.Threading.Tasks.Task(Of WcfService.DbProcessResult) Implements WcfService.IOrderManagementService.DeleteCustomerDtoAsync
            Return MyBase.Channel.DeleteCustomerDtoAsync(customerId)
        End Function
        
        Public Function CustomerDtoExists(ByVal customerId As String) As Boolean Implements WcfService.IOrderManagementService.CustomerDtoExists
            Return MyBase.Channel.CustomerDtoExists(customerId)
        End Function
        
        Public Function CustomerDtoExistsAsync(ByVal customerId As String) As System.Threading.Tasks.Task(Of Boolean) Implements WcfService.IOrderManagementService.CustomerDtoExistsAsync
            Return MyBase.Channel.CustomerDtoExistsAsync(customerId)
        End Function
    End Class
End Namespace
