'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WcfService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OrderDto", [Namespace]:="http://schemas.datacontract.org/2004/07/OrderManagement.WcfService.Dto"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OrderDto
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerDtoField As WcfService.CustomerDto
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InvoiceNoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderDateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderDetailDtoesField() As WcfService.OrderDetailDto
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderTypeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ShipDateField As System.Nullable(Of Date)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomerDto() As WcfService.CustomerDto
            Get
                Return Me.CustomerDtoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomerDtoField, value) <> true) Then
                    Me.CustomerDtoField = value
                    Me.RaisePropertyChanged("CustomerDto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomerId() As Integer
            Get
                Return Me.CustomerIdField
            End Get
            Set
                If (Me.CustomerIdField.Equals(value) <> true) Then
                    Me.CustomerIdField = value
                    Me.RaisePropertyChanged("CustomerId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InvoiceNo() As String
            Get
                Return Me.InvoiceNoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InvoiceNoField, value) <> true) Then
                    Me.InvoiceNoField = value
                    Me.RaisePropertyChanged("InvoiceNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderDate() As System.Nullable(Of Date)
            Get
                Return Me.OrderDateField
            End Get
            Set
                If (Me.OrderDateField.Equals(value) <> true) Then
                    Me.OrderDateField = value
                    Me.RaisePropertyChanged("OrderDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderDetailDtoes() As WcfService.OrderDetailDto()
            Get
                Return Me.OrderDetailDtoesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrderDetailDtoesField, value) <> true) Then
                    Me.OrderDetailDtoesField = value
                    Me.RaisePropertyChanged("OrderDetailDtoes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderId() As Integer
            Get
                Return Me.OrderIdField
            End Get
            Set
                If (Me.OrderIdField.Equals(value) <> true) Then
                    Me.OrderIdField = value
                    Me.RaisePropertyChanged("OrderId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OrderType() As Integer
            Get
                Return Me.OrderTypeField
            End Get
            Set
                If (Me.OrderTypeField.Equals(value) <> true) Then
                    Me.OrderTypeField = value
                    Me.RaisePropertyChanged("OrderType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ShipDate() As System.Nullable(Of Date)
            Get
                Return Me.ShipDateField
            End Get
            Set
                If (Me.ShipDateField.Equals(value) <> true) Then
                    Me.ShipDateField = value
                    Me.RaisePropertyChanged("ShipDate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CustomerDto", [Namespace]:="http://schemas.datacontract.org/2004/07/OrderManagement.WcfService.Dto"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CustomerDto
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PhoneField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PostCodeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address() As String
            Get
                Return Me.AddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddressField, value) <> true) Then
                    Me.AddressField = value
                    Me.RaisePropertyChanged("Address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomerId() As Integer
            Get
                Return Me.CustomerIdField
            End Get
            Set
                If (Me.CustomerIdField.Equals(value) <> true) Then
                    Me.CustomerIdField = value
                    Me.RaisePropertyChanged("CustomerId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Phone() As String
            Get
                Return Me.PhoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PhoneField, value) <> true) Then
                    Me.PhoneField = value
                    Me.RaisePropertyChanged("Phone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PostCode() As String
            Get
                Return Me.PostCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PostCodeField, value) <> true) Then
                    Me.PostCodeField = value
                    Me.RaisePropertyChanged("PostCode")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OrderDetailDto", [Namespace]:="http://schemas.datacontract.org/2004/07/OrderManagement.WcfService.Dto"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OrderDetailDto
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LinkField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderDetailIdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrderIdField As Integer

        <System.Runtime.Serialization.OptionalFieldAttribute()>
        Private ProductDtoField As WcfService.ProductDto

        <System.Runtime.Serialization.OptionalFieldAttribute()>
        Private ProductIdField As Integer

        <System.Runtime.Serialization.OptionalFieldAttribute()>
        Private PurchasePriceField As System.Nullable(Of Decimal)

        <System.Runtime.Serialization.OptionalFieldAttribute()>
        Private QuantityField As System.Nullable(Of Integer)

        <System.Runtime.Serialization.OptionalFieldAttribute()>
        Private SoldPriceField As System.Nullable(Of Decimal)

        <System.Runtime.Serialization.OptionalFieldAttribute()>
        Private StatusField As Integer

        <Global.System.ComponentModel.BrowsableAttribute(False)>
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = Value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property Link() As String
            Get
                Return Me.LinkField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LinkField, Value) <> True) Then
                    Me.LinkField = Value
                    Me.RaisePropertyChanged("Link")
                End If
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property OrderDetailId() As Integer
            Get
                Return Me.OrderDetailIdField
            End Get
            Set
                If (Me.OrderDetailIdField.Equals(Value) <> True) Then
                    Me.OrderDetailIdField = Value
                    Me.RaisePropertyChanged("OrderDetailId")
                End If
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property OrderId() As Integer
            Get
                Return Me.OrderIdField
            End Get
            Set
                If (Me.OrderIdField.Equals(Value) <> True) Then
                    Me.OrderIdField = Value
                    Me.RaisePropertyChanged("OrderId")
                End If
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property ProductDto() As WcfService.ProductDto
            Get
                Return Me.ProductDtoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductDtoField, Value) <> True) Then
                    Me.ProductDtoField = Value
                    Me.RaisePropertyChanged("ProductDto")
                End If
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property ProductId() As Integer
            Get
                Return Me.ProductIdField
            End Get
            Set
                If (Me.ProductIdField.Equals(Value) <> True) Then
                    Me.ProductIdField = Value
                    Me.RaisePropertyChanged("ProductId")
                End If
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property PurchasePrice() As System.Nullable(Of Decimal)
            Get
                Return Me.PurchasePriceField
            End Get
            Set
                If (Me.PurchasePriceField.Equals(Value) <> True) Then
                    Me.PurchasePriceField = Value
                    Me.RaisePropertyChanged("PurchasePrice")
                End If
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property Quantity() As System.Nullable(Of Integer)
            Get
                Return Me.QuantityField
            End Get
            Set
                If (Me.QuantityField.Equals(Value) <> True) Then
                    Me.QuantityField = Value
                    Me.RaisePropertyChanged("Quantity")
                End If
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property SoldPrice() As System.Nullable(Of Decimal)
            Get
                Return Me.SoldPriceField
            End Get
            Set
                If (Me.SoldPriceField.Equals(Value) <> True) Then
                    Me.SoldPriceField = Value
                    Me.RaisePropertyChanged("SoldPrice")
                End If
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property Status() As Integer
            Get
                Return Me.StatusField
            End Get
            Set
                If (Me.StatusField.Equals(Value) <> True) Then
                    Me.StatusField = Value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(),
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),
     System.Runtime.Serialization.DataContractAttribute(Name:="ProductDto", [Namespace]:="http://schemas.datacontract.org/2004/07/OrderManagement.WcfService.Dto"),
     System.SerializableAttribute()>
    Partial Public Class ProductDto
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged

        <System.NonSerializedAttribute()>
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject

        <System.Runtime.Serialization.OptionalFieldAttribute()>
        Private ProductIdField As Integer

        <System.Runtime.Serialization.OptionalFieldAttribute()>
        Private ProductNameField As String

        <System.Runtime.Serialization.OptionalFieldAttribute()>
        Private ProductNameJpField As String

        <Global.System.ComponentModel.BrowsableAttribute(False)>
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = Value
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property ProductId() As Integer
            Get
                Return Me.ProductIdField
            End Get
            Set
                If (Me.ProductIdField.Equals(Value) <> True) Then
                    Me.ProductIdField = Value
                    Me.RaisePropertyChanged("ProductId")
                End If
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property ProductName() As String
            Get
                Return Me.ProductNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductNameField, Value) <> True) Then
                    Me.ProductNameField = Value
                    Me.RaisePropertyChanged("ProductName")
                End If
            End Set
        End Property

        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property ProductNameJp() As String
            Get
                Return Me.ProductNameJpField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductNameJpField, Value) <> True) Then
                    Me.ProductNameJpField = Value
                    Me.RaisePropertyChanged("ProductNameJp")
                End If
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WcfService.IOrderManagementService")>
    Public Interface IOrderManagementService

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/GetOrderDtoes", ReplyAction:="http://tempuri.org/IOrderManagementService/GetOrderDtoesResponse")>
        Function GetOrderDtoes() As WcfService.OrderDto()

        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderManagementService/GetOrderDtoes", ReplyAction:="http://tempuri.org/IOrderManagementService/GetOrderDtoesResponse")>
        Function GetOrderDtoesAsync() As System.Threading.Tasks.Task(Of WcfService.OrderDto())
    End Interface

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IOrderManagementServiceChannel
        Inherits WcfService.IOrderManagementService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class OrderManagementServiceClient
        Inherits System.ServiceModel.ClientBase(Of WcfService.IOrderManagementService)
        Implements WcfService.IOrderManagementService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetOrderDtoes() As WcfService.OrderDto() Implements WcfService.IOrderManagementService.GetOrderDtoes
            Return MyBase.Channel.GetOrderDtoes
        End Function
        
        Public Function GetOrderDtoesAsync() As System.Threading.Tasks.Task(Of WcfService.OrderDto()) Implements WcfService.IOrderManagementService.GetOrderDtoesAsync
            Return MyBase.Channel.GetOrderDtoesAsync
        End Function
    End Class
End Namespace
